<?php
/**
 * Our list of events.
 *
 * @package wsal
 * @subpackage wsal-woocommerce
 */

// phpcs:disable WordPress.WP.I18n.UnorderedPlaceholdersText 
// phpcs:disable WordPress.WP.I18n.MissingTranslatorsComment

$custom_alerts = array(
	__( 'WooCommerce', 'wsal-woocommerce' ) => array(
		__( 'Products', 'wsal-woocommerce' )         => array(
			array(
				9000,
				WSAL_LOW,
				__( 'User created a new product', 'wsal-woocommerce' ),
				__( 'Created a new product called %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'created',
			),
			array(
				9001,
				WSAL_MEDIUM,
				__( 'User published a product', 'wsal-woocommerce' ),
				__( 'Published the product called %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'published',
			),
			array(
				9003,
				WSAL_LOW,
				__( 'User changed the category of a product', 'wsal-woocommerce' ),
				__( 'Changed the category(ies) of the product %ProductTitle% to %NewCategories%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous categories', 'wsal-woocommerce' ) => '%OldCategories%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9004,
				WSAL_INFORMATIONAL,
				__( 'User modified the short description of a product', 'wsal-woocommerce' ),
				__( 'Changed the short description of the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9005,
				WSAL_LOW,
				__( 'User modified the text of a product', 'wsal-woocommerce' ),
				__( 'Changed the text of the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9006,
				WSAL_LOW,
				__( 'User changed the URL of a product', 'wsal-woocommerce' ),
				__( 'Changed the URL of the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous URL', 'wsal-woocommerce' ) => '%OldUrl%',
					__( 'New URL', 'wsal-woocommerce' )    => '%NewUrl%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9007,
				WSAL_MEDIUM,
				__( 'User changed the Product Data of a product', 'wsal-woocommerce' ),
				__( 'Changed the type of the product %ProductTitle% to %NewType%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous type', 'wsal-woocommerce' ) => '%OldType%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9008,
				WSAL_INFORMATIONAL,
				__( 'User changed the date of a product', 'wsal-woocommerce' ),
				__( 'Changed the date of the product %ProductTitle% to %NewDate%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous date', 'wsal-woocommerce' ) => '%OldDate%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9009,
				WSAL_MEDIUM,
				__( 'User changed the visibility of a product', 'wsal-woocommerce' ),
				__( 'Changed the visibility of the product %ProductTitle% to %NewVisibility%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous visibility', 'wsal-woocommerce' ) => '%OldVisibility%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9010,
				WSAL_MEDIUM,
				__( 'User modified the product', 'wsal-woocommerce' ),
				__( 'Modified the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9011,
				E_NOTICE,
				__( 'User modified the draft product', 'wsal-woocommerce' ),
				__( 'Modified the draft product %ProductTitle%.', 'wsal-woocommerce' ),
				array(),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'',
			),
			array(
				9012,
				WSAL_HIGH,
				__( 'User moved a product to trash', 'wsal-woocommerce' ),
				__( 'Moved the product %ProductTitle% to trash.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
				),
				array(),
				'woocommerce-product',
				'deleted',
			),
			array(
				9013,
				WSAL_MEDIUM,
				__( 'User permanently deleted a product', 'wsal-woocommerce' ),
				__( 'Permanently deleted the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
				),
				array(),
				'woocommerce-product',
				'deleted',
			),
			array(
				9014,
				WSAL_HIGH,
				__( 'User restored a product from the trash', 'wsal-woocommerce' ),
				__( 'Restored the product %ProductTitle% from trash.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'restored',
			),
			array(
				9015,
				WSAL_MEDIUM,
				__( 'User changed status of a product', 'wsal-woocommerce' ),
				__( 'Changed the status of the product %ProductTitle% to %NewStatus%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Previous status', 'wsal-woocommerce' ) => '%OldStatus%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9072,
				WSAL_INFORMATIONAL,
				__( 'User opened a product in the editor', 'wsal-woocommerce' ),
				__( 'Opened the product %ProductTitle% in the editor.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'opened',
			),
			array(
				9073,
				WSAL_INFORMATIONAL,
				__( 'User viewed a product', 'wsal-woocommerce' ),
				__( 'Viewed the product %ProductTitle% page.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'viewed',
			),
			array(
				9077,
				WSAL_MEDIUM,
				__( 'User renamed a product', 'wsal-woocommerce' ),
				__( 'Renamed the product %OldTitle% to %NewTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'renamed',
			),

			array(
				9016,
				WSAL_MEDIUM,
				__( 'User changed type of a price', 'wsal-woocommerce' ),
				__( 'Changed the %PriceType% price of the product %ProductTitle% to %NewPrice%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous price', 'wsal-woocommerce' ) => '%OldPrice%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9017,
				WSAL_MEDIUM,
				__( 'User changed the SKU of a product', 'wsal-woocommerce' ),
				__( 'Changed the SKU of the product %ProductTitle% to %NewSku%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous SKU', 'wsal-woocommerce' ) => '%OldSku%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9018,
				WSAL_LOW,
				__( 'User changed the stock status of a product', 'wsal-woocommerce' ),
				__( 'Changed the stock status of the product %ProductTitle% to %NewStatus%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous stock status', 'wsal-woocommerce' ) => '%OldStatus%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9020,
				WSAL_MEDIUM,
				__( 'User set a product type', 'wsal-woocommerce' ),
				__( 'Changed the type of the product %ProductTitle% to %NewType%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous type', 'wsal-woocommerce' ) => '%OldType%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9021,
				WSAL_INFORMATIONAL,
				__( 'User changed the weight of a product', 'wsal-woocommerce' ),
				__( 'Changed the weight of the product %ProductTitle% to %NewWeight%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous weight', 'wsal-woocommerce' ) => '%OldWeight%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9022,
				WSAL_INFORMATIONAL,
				__( 'User changed the dimensions of a product', 'wsal-woocommerce' ),
				__( 'Changed the %DimensionType% dimensions of the product %ProductTitle% to %NewDimension%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous value', 'wsal-woocommerce' ) => '%OldDimension%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9023,
				WSAL_MEDIUM,
				__( 'User added the Downloadable File to a product', 'wsal-woocommerce' ),
				__( 'Added the downloadable file %FileName% to the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'File URL', 'wsal-woocommerce' )   => '%FileUrl%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9024,
				WSAL_MEDIUM,
				__( 'User Removed the Downloadable File from a product', 'wsal-woocommerce' ),
				__( 'Removed the downloadable file %FileName% from the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'File URL', 'wsal-woocommerce' )   => '%FileUrl%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9025,
				WSAL_INFORMATIONAL,
				__( 'User changed the name of a Downloadable File in a product', 'wsal-woocommerce' ),
				__( 'Changed the name of the downloadable file %OldName% to %NewName% in the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous file name', 'wsal-woocommerce' ) => '%OldName%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9026,
				WSAL_MEDIUM,
				__( 'User changed the URL of the Downloadable File in a product', 'wsal-woocommerce' ),
				__( 'Changed the URL of the downloadable file to the product %ProductTitle%', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'File name', 'wsal-woocommerce' )  => '%FileName%',
					__( 'Previous URL', 'wsal-woocommerce' ) => '%OldUrl%',
					__( 'New URL', 'wsal-woocommerce' )    => '%NewUrl%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9042,
				WSAL_INFORMATIONAL,
				__( 'User changed the catalog visibility of a product', 'wsal-woocommerce' ),
				__( 'Changed the product visibility of the product %ProductTitle% to %NewVisibility%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous visibility setting', 'wsal-woocommerce' ) => '%OldVisibility%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9043,
				WSAL_INFORMATIONAL,
				__( 'User changed the setting Featured Product of a product', 'wsal-woocommerce' ),
				__( 'Changed the status of the setting <strong>Featured Product</strong> for the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'enabled',
			),
			array(
				9044,
				WSAL_INFORMATIONAL,
				__( 'User changed the Allow Backorders setting of a product', 'wsal-woocommerce' ),
				__( 'Changed the Allow Backorders setting for the product %ProductTitle% to %NewStatus%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous status', 'wsal-woocommerce' ) => '%OldStatus%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9045,
				WSAL_MEDIUM,
				__( 'User added/removed products to upsell of a product', 'wsal-woocommerce' ),
				__( 'Products to the Upsell setting in product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'New product in Upsells', 'wsal-woocommerce' ) => '%UpsellTitle%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'added',
			),
			array(
				9046,
				WSAL_MEDIUM,
				__( 'User added/removed products to cross-sells of a product', 'wsal-woocommerce' ),
				__( 'Products to the Cross-sell setting in product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'New product in Cross-sells', 'wsal-woocommerce' ) => '%CrossSellTitle%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'added',
			),

			array(
				9095,
				WSAL_LOW,
				__( 'Added or deleted a product image', 'wsal-woocommerce' ),
				__( 'The product image of the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Image name', 'wsal-woocommerce' ) => '%name%',
					__( 'Image path', 'wsal-woocommerce' ) => '%path%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'added',
			),
			array(
				9096,
				WSAL_LOW,
				__( 'Modified a product image', 'wsal-woocommerce' ),
				__( 'Changed the product image of the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous image name', 'wsal-woocommerce' ) => '%old_name%',
					__( 'Previous image path', 'wsal-woocommerce' ) => '%old_path%',
					__( 'New image name', 'wsal-woocommerce' ) => '%name%',
					__( 'New image path', 'wsal-woocommerce' ) => '%path%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9097,
				WSAL_LOW,
				__( 'Modified the download limit of the product', 'wsal-woocommerce' ),
				__( 'Changed the download limit of the product %product_name% to %new_value%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%ID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous value', 'wsal-woocommerce' ) => '%previous_value%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9098,
				WSAL_LOW,
				__( 'Modified the download expiry setting of the product', 'wsal-woocommerce' ),
				__( 'Changed the download expire setting of the product %product_name% to %new_value%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%ID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous value', 'wsal-woocommerce' ) => '%previous_value%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9099,
				WSAL_LOW,
				__( 'A product was downloaded', 'wsal-woocommerce' ),
				__( 'Downloaded the product %product_name%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%ID%',
					__( 'User email', 'wsal-woocommerce' ) => '%email_address%',
				),
				array(),
				'woocommerce-product',
				'modified',
			),

			array(
				9105,
				WSAL_LOW,
				__( 'System changed the stock quantity of a product', 'wsal-woocommerce' ),
				__( 'The stock quantity of the product %ProductTitle% was changed to %NewValue% due to a purchase.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'User name', 'wsal-woocommerce' )  => '%Username%',
					__( 'Order name', 'wsal-woocommerce' ) => '%StockOrderID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous quantity', 'wsal-woocommerce' ) => '%OldValue%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9106,
				WSAL_LOW,
				__( 'Third-party plugin changed the stock quantity of a product', 'wsal-woocommerce' ),
				__( 'The stock quantity of the product %ProductTitle% was changed to %NewValue% via third party system.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous quantity', 'wsal-woocommerce' ) => '%OldValue%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9113,
				WSAL_MEDIUM,
				__( 'The Tax status of a product has been modified', 'wsal-woocommerce' ),
				__( 'Changed the Tax status of the product %ProductTitle% to %new_tax_status%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous tax status', 'wsal-woocommerce' ) => '%old_tax_status%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9114,
				WSAL_MEDIUM,
				__( 'The Tax class of a product has been modified', 'wsal-woocommerce' ),
				__( 'Changed the Tax class of the product %ProductTitle% to %new_tax_class%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous tax class', 'wsal-woocommerce' ) => '%old_tax_class%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),

			array(
				9019,
				WSAL_LOW,
				__( 'User changed the stock quantity', 'wsal-woocommerce' ),
				__( 'Changed the stock quantity of the product %ProductTitle% to %NewValue%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%PostID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous quantity', 'wsal-woocommerce' ) => '%OldValue%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),

			array(
				9047,
				WSAL_LOW,
				__( 'Added a new attribute of a product', 'wsal-woocommerce' ),
				__( 'Added a new attribute caled %AttributeName% to the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%ProductID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Attribute value', 'wsal-woocommerce' ) => '%AttributeValue%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'added',
			),
			array(
				9048,
				WSAL_LOW,
				__( 'Modified the value of an attribute of a product', 'wsal-woocommerce' ),
				__( 'Modified the value of the attribute %AttributeName$ in the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%ProductID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous attribute value', 'wsal-woocommerce' ) => '%OldValue%',
					__( 'New attribute value', 'wsal-woocommerce' ) => '%NewValue%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
			array(
				9049,
				WSAL_LOW,
				__( 'Changed the name of an attribute of a product', 'wsal-woocommerce' ),
				__( 'Renamed the attribute %OldValue% to %NewValue% in the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%ProductID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'renamed',
			),
			array(
				9050,
				WSAL_LOW,
				__( 'Deleted an attribute of a product', 'wsal-woocommerce' ),
				__( 'Deleted the attribute %AttributeName% from the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%ProductID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Attribute value', 'wsal-woocommerce' ) => '%AttributeValue%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'deleted',
			),
			array(
				9051,
				WSAL_LOW,
				__( 'Set the attribute visibility of a product', 'wsal-woocommerce' ),
				__( 'Changed the visibility of the attribute %AttributeName% to %AttributeVisiblilty% in the the product %ProductTitle%.', 'wsal-woocommerce' ),
				array(
					__( 'Product ID', 'wsal-woocommerce' ) => '%ProductID%',
					__( 'Product status', 'wsal-woocommerce' ) => '%ProductStatus%',
					__( 'Previous visibility', 'wsal-woocommerce' ) => '%OldAttributeVisiblilty%',
				),
				array(
					__( 'View product in editor', 'wsal-woocommerce' ) => '%EditorLinkProduct%',
				),
				'woocommerce-product',
				'modified',
			),
		),

		__( 'Store', 'wsal-woocommerce' )            => array(
			array(
				9027,
				WSAL_HIGH,
				__( 'User changed the Weight Unit', 'wsal-woocommerce' ),
				__( 'Changed the <strong>weight unit</strong> of the store to %NewUnit%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous weight unit', 'wsal-woocommerce' ) => '%OldUnit%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9028,
				WSAL_HIGH,
				__( 'User changed the Dimensions Unit', 'wsal-woocommerce' ),
				__( 'Changed the <strong>dimensions unit</strong> of the store to %NewUnit%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous dimensions unit', 'wsal-woocommerce' ) => '%OldUnit%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9029,
				WSAL_HIGH,
				__( 'User changed the Base Location', 'wsal-woocommerce' ),
				__( 'Changed the <strong>base location</strong> of the store to %NewLocation%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous address', 'wsal-woocommerce' ) => '%OldLocation%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9030,
				WSAL_HIGH,
				__( 'User enabled/disabled taxes', 'wsal-woocommerce' ),
				__( 'Changed the status of the <strong>Taxes</strong> store setting.', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'enabled',
			),
			array(
				9031,
				WSAL_HIGH,
				__( 'User changed the currency', 'wsal-woocommerce' ),
				__( 'Changed the <strong>currency</strong> of the store to %NewCurrency%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous currency', 'wsal-woocommerce' ) => '%OldCurrency%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9032,
				WSAL_HIGH,
				__( 'User enabled/disabled the use of coupons during checkout', 'wsal-woocommerce' ),
				__( 'Changed the status of the store setting <strong>use of coupons during checkout</strong>.', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'enabled',
			),
			array(
				9033,
				WSAL_MEDIUM,
				__( 'User enabled/disabled guest checkout', 'wsal-woocommerce' ),
				__( 'Changed the status of the store setting <strong>Guest checkout</strong>.', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'enabled',
			),
			array(
				9034,
				WSAL_HIGH,
				__( 'User enabled/disabled Cash on delivery', 'wsal-woocommerce' ),
				__( 'Changed the status of the store setting <strong>cash on delivery</strong>', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'enabled',
			),
			array(
				9085,
				WSAL_HIGH,
				__( 'User modified selling location(s)', 'wsal-woocommerce' ),
				__( 'Changed the store setting <strong>Selling location(s)</strong> to %new%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous setting', 'wsal-woocommerce' ) => '%old%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9086,
				WSAL_HIGH,
				__( 'User modified excluded selling location(s)', 'wsal-woocommerce' ),
				__( 'Changed the <strong>list of excluded countries to sell to</strong> setting in the store.', 'wsal-woocommerce' ),
				array(
					__( 'Previous list of countries', 'wsal-woocommerce' ) => '%old%',
					__( 'New list of countries', 'wsal-woocommerce' ) => '%new%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9087,
				WSAL_HIGH,
				__( 'User modified exclusive selling location(s)', 'wsal-woocommerce' ),
				__( 'Changed the <strong>list of countries to sell to</strong> setting in the store.', 'wsal-woocommerce' ),
				array(
					__( 'Previous list of countries', 'wsal-woocommerce' ) => '%old%',
					__( 'New list of countries', 'wsal-woocommerce' ) => '%new%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9088,
				WSAL_HIGH,
				__( 'User modified shipping location(s)', 'wsal-woocommerce' ),
				__( 'Changed the <strong>Shipping location(s)</strong> setting in the store.', 'wsal-woocommerce' ),
				array(
					__( 'Previous setting', 'wsal-woocommerce' ) => '%old%',
					__( 'New Setting', 'wsal-woocommerce' ) => '%new%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9089,
				WSAL_HIGH,
				__( 'User modified exclusive shipping location(s)', 'wsal-woocommerce' ),
				__( 'Changed the <strong>List of specific countries to</strong> ship to setting in the store.', 'wsal-woocommerce' ),
				array(
					__( 'Previous list of countries', 'wsal-woocommerce' ) => '%old%',
					__( 'New list of countries', 'wsal-woocommerce' ) => '%new%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9090,
				WSAL_HIGH,
				__( 'User modified default customer location', 'wsal-woocommerce' ),
				__( 'Changed the <strong>Default customer location</strong> setting to %new%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous location', 'wsal-woocommerce' ) => '%old%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9091,
				WSAL_HIGH,
				__( 'User modified the cart page', 'wsal-woocommerce' ),
				__( 'Changed the store\'s <strong>Cart page</strong> to %new%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous page', 'wsal-woocommerce' ) => '%old%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9092,
				WSAL_HIGH,
				__( 'User modified the checkout page', 'wsal-woocommerce' ),
				__( 'Changed the store\'s <strong>Checkout page</strong> to %new%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous page', 'wsal-woocommerce' ) => '%old%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9093,
				WSAL_HIGH,
				__( 'User modified the my account page', 'wsal-woocommerce' ),
				__( 'Changed the store\'s <strong>My account page</strong> to %new%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous page', 'wsal-woocommerce' ) => '%old%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9094,
				WSAL_HIGH,
				__( 'User modified the terms and conditions page', 'wsal-woocommerce' ),
				__( 'Changed the store\'s <strong>Terms and conditions page</strong> to %new%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous page', 'wsal-woocommerce' ) => '%old%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9100,
				WSAL_MEDIUM,
				__( 'Changed the status of the Enable product reviews setting in the store', 'wsal-woocommerce' ),
				__( 'Changed the status of the <strong>Enable product reviews</strong> setting in the store.', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9107,
				WSAL_LOW,
				__( 'Changed the status of the Show "verified owner" label on customer reviews setting in the store', 'wsal-woocommerce' ),
				__( 'Changed the status of the <strong>Show "verified owner" label on customer reviews</strong> setting in the store.', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9108,
				WSAL_LOW,
				__( 'Changed the status of the Reviews can only be left by "verified owners" setting in the store', 'wsal-woocommerce' ),
				__( 'Changed the status of the <strong>Reviews can only be left by "verified owners"</strong> setting in the store.', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9109,
				WSAL_MEDIUM,
				__( 'Changed the status of the Star rating on reviews setting in the store', 'wsal-woocommerce' ),
				__( 'Changed the status of the <strong>Star rating on reviews</strong> setting in the store.', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9110,
				WSAL_MEDIUM,
				__( 'Changed the status of the Star ratings should be required setting in the store', 'wsal-woocommerce' ),
				__( 'Changed the status of the <strong>Star ratings should be required</strong> setting in the store.', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9111,
				WSAL_MEDIUM,
				__( 'A Checkout endpoint has been modified', 'wsal-woocommerce' ),
				__( 'Changed the <strong>Checkout endpoint</strong> %endpoint_name% to %new_value%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous endpoint value', 'wsal-woocommerce' ) => '%old%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9112,
				WSAL_MEDIUM,
				__( 'An Account endpoint has been modified', 'wsal-woocommerce' ),
				__( 'Changed the <strong>Account endpoint</strong> %endpoint_name% to %new_value%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous endpoint value', 'wsal-woocommerce' ) => '%old%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9115,
				WSAL_MEDIUM,
				__( 'The Currency position setting has been modified', 'wsal-woocommerce' ),
				__( 'Changed the <strong>Currency position</strong> setting to %new_setting%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous setting', 'wsal-woocommerce' ) => '%%old_setting%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9116,
				WSAL_MEDIUM,
				__( 'The Thousand separator setting has been modified', 'wsal-woocommerce' ),
				__( 'Changed the <strong>Thousand separator</strong> setting in the Currency options to %new_setting%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous setting', 'wsal-woocommerce' ) => '%%old_setting%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9117,
				WSAL_MEDIUM,
				__( 'The Decimal separator setting has been modified', 'wsal-woocommerce' ),
				__( 'Changed the <strong>Decimal separator</strong> setting in the Currency options to %new_setting%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous setting', 'wsal-woocommerce' ) => '%%old_setting%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9118,
				WSAL_MEDIUM,
				__( 'The Number of decimals position setting has been modified', 'wsal-woocommerce' ),
				__( 'Changed the <strong>Number of decimals</strong> setting in the Currency options to %new_setting%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous setting', 'wsal-woocommerce' ) => '%%old_setting%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
		),

		__( 'Payment Gateways', 'wsal-woocommerce' ) => array(
			array(
				9074,
				WSAL_HIGH,
				__( 'User enabled/disabled a payment gateway', 'wsal-woocommerce' ),
				__( 'Changed the status of the payment gateway %GatewayName%.', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'enabled',
			),
			array(
				9075,
				E_CRITICAL,
				__( 'User disabled a payment gateway', 'wsal-woocommerce' ),
				__( 'User disabled a payment gateway', 'wsal-woocommerce' ),
				array(
					__( 'The payment gateway', 'wsal-woocommerce' ) => '%GatewayName%',
				),
				array(),
				'woocommerce-store',
				'',
			),
			array(
				9076,
				WSAL_HIGH,
				__( 'User modified a payment gateway', 'wsal-woocommerce' ),
				__( 'Changed the settings of the %GatewayName% payment gateway.', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'modified',
			),
		),

		__( 'Tax Settings', 'wsal-woocommerce' )     => array(
			array(
				9078,
				WSAL_LOW,
				__( 'User modified prices with tax option', 'wsal-woocommerce' ),
				__( 'Changed the store setting <strong>Prices entered with tax</strong> to %TaxStatus% taxes.', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9079,
				WSAL_LOW,
				__( 'User modified tax calculation base', 'wsal-woocommerce' ),
				__( 'Changed the store setting <strong>Calculate tax based on</strong> to %Setting%', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9080,
				WSAL_MEDIUM,
				__( 'User modified shipping tax class', 'wsal-woocommerce' ),
				__( 'Changed the store setting <strong>Shipping tax class</strong> to %Setting%', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9081,
				WSAL_MEDIUM,
				__( 'User enabled/disabled rounding of tax', 'wsal-woocommerce' ),
				__( 'Changed the status of the store tax setting <strong>Rounding</strong> of tax at subtotal level.', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'enabled',
			),
			array(
				9082,
				WSAL_MEDIUM,
				__( 'User modified a shipping zone', 'wsal-woocommerce' ),
				__( 'The shipping zone %ShippingZoneName% on the WooCommerce store', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-store',
				'created',
			),
		),

		__( 'WC Categories', 'wsal-woocommerce' )    => array(
			array(
				9002,
				WSAL_INFORMATIONAL,
				__( 'User created a new product category', 'wsal-woocommerce' ),
				__( 'Created new product category called %CategoryName%.', 'wsal-woocommerce' ),
				array(
					__( 'Category slug', 'wsal-woocommerce' ) => '%Slug%',
				),
				array(
					__( 'View category', 'wsal-woocommerce' ) => '%ProductCatLink%',
				),
				'woocommerce-category',
				'created',
			),
			array(
				9052,
				WSAL_MEDIUM,
				__( 'User deleted a product category', 'wsal-woocommerce' ),
				__( 'Deleted the product category called %CategoryName%.', 'wsal-woocommerce' ),
				array(
					__( 'Category slug', 'wsal-woocommerce' ) => '%CategorySlug%',
				),
				array(),
				'woocommerce-category',
				'deleted',
			),
			array(
				9053,
				WSAL_INFORMATIONAL,
				__( 'User changed the slug of a product category', 'wsal-woocommerce' ),
				__( 'Changed the slug of the product category called %CategoryName%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous category slug', 'wsal-woocommerce' ) => '%OldSlug%',
					__( 'New category slug', 'wsal-woocommerce' ) => '%NewSlug%',
				),
				array(
					__( 'View category', 'wsal-woocommerce' ) => '%ProductCatLink%',
				),
				'woocommerce-category',
				'modified',
			),
			array(
				9054,
				WSAL_MEDIUM,
				__( 'User changed the parent category of a product category', 'wsal-woocommerce' ),
				__( 'Changed the parent of the product category %CategoryName% to %NewParentCat%.', 'wsal-woocommerce' ),
				array(
					__( 'Category slug', 'wsal-woocommerce' ) => '%CategorySlug%',
					__( 'Previous parent', 'wsal-woocommerce' ) => '%OldParentCat%',
				),
				array(
					__( 'View category', 'wsal-woocommerce' ) => '%ProductCatLink%',
				),
				'woocommerce-category',
				'modified',
			),
			array(
				9055,
				WSAL_INFORMATIONAL,
				__( 'User changed the display type of a product category', 'wsal-woocommerce' ),
				__( 'Changed the display type of the product category %name% to %NewDisplayType%.', 'wsal-woocommerce' ),
				array(
					__( 'Category slug', 'wsal-woocommerce' ) => '%CategorySlug%',
					__( 'Previous display type', 'wsal-woocommerce' ) => '%OldDisplayType%',
				),
				array(
					__( 'View category', 'wsal-woocommerce' ) => '%ProductCatLink%',
				),
				'woocommerce-category',
				'modified',
			),
			array(
				9056,
				WSAL_LOW,
				__( 'User changed the name of a product category', 'wsal-woocommerce' ),
				__( 'Renamed the product category %OldName% to %NewName%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous category name', 'wsal-woocommerce' ) => '%OldName%',
					__( 'Category slug', 'wsal-woocommerce' ) => '%CategorySlug%',
				),
				array(
					__( 'View category', 'wsal-woocommerce' ) => '%ProductCatLink%',
				),
				'woocommerce-category',
				'renamed',
			),
		),

		__( 'WC Tags', 'wsal-woocommerce' )          => array(
			array(
				9101,
				WSAL_INFORMATIONAL,
				__( 'User created a new product tag', 'wsal-woocommerce' ),
				__( 'Created the tag %CategoryName%.', 'wsal-woocommerce' ),
				array(
					__( 'Slug', 'wsal-woocommerce' ) => '%Slug%',
				),
				array(
					__( 'View product tag', 'wsal-woocommerce' ) => '%ProductTagLink%',
				),
				'woocommerce-tag',
				'created',
			),
			array(
				9102,
				WSAL_INFORMATIONAL,
				__( 'User deleted a product tag', 'wsal-woocommerce' ),
				__( 'Deleted the tag %Name%.', 'wsal-woocommerce' ),
				array(
					__( 'Slug', 'wsal-woocommerce' ) => '%Slug%',
				),
				array(),
				'woocommerce-tag',
				'deleted',
			),
			array(
				9103,
				WSAL_INFORMATIONAL,
				__( 'User renamed product tag', 'wsal-woocommerce' ),
				__( 'Renamed the tag %OldName% to %NewName%.', 'wsal-woocommerce' ),
				array(
					__( 'Slug', 'wsal-woocommerce' ) => '%Slug%',
				),
				array(
					__( 'View product tag', 'wsal-woocommerce' ) => '%ProductTagLink%',
				),
				'woocommerce-tag',
				'renamed',
			),
			array(
				9104,
				WSAL_INFORMATIONAL,
				__( 'User changed product tag slug', 'wsal-woocommerce' ),
				__( 'Changed the slug of the tag %TagName% to %NewSlug%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous slug', 'wsal-woocommerce' ) => '%OldSlug%',
				),
				array(
					__( 'View product tag', 'wsal-woocommerce' ) => '%ProductTagLink%',
				),
				'woocommerce-tag',
				'modified',
			),
		),

		__( 'Attributes', 'wsal-woocommerce' )       => array(
			array(
				9057,
				WSAL_MEDIUM,
				__( 'User created a new attribute', 'wsal-woocommerce' ),
				__( 'Created a new attribute in WooCommerce called %AttributeName%.', 'wsal-woocommerce' ),
				array(
					__( 'Attribute slug', 'wsal-woocommerce' ) => '%AttributeSlug%',
				),
				array(),
				'woocommerce-store',
				'created',
			),
			array(
				9058,
				WSAL_LOW,
				__( 'User deleted an attribute', 'wsal-woocommerce' ),
				__( 'Deleted the WooCommerce attribute %AttributeName%.', 'wsal-woocommerce' ),
				array(
					__( 'Attribute slug', 'wsal-woocommerce' ) => '%AttributeSlug%',
				),
				array(),
				'woocommerce-store',
				'deleted',
			),
			array(
				9059,
				WSAL_LOW,
				__( 'User changed the slug of an attribute', 'wsal-woocommerce' ),
				__( 'Changed the slug of the WooCommerce attribute %AttributeName% to %NewSlug%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous slug', 'wsal-woocommerce' ) => '%OldSlug%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9060,
				WSAL_LOW,
				__( 'User changed the name of an attribute', 'wsal-woocommerce' ),
				__( 'Renamed the WooCommerce attribute %AttributeName% to %NewName%.', 'wsal-woocommerce' ),
				array(
					__( 'Attribute slug', 'wsal-woocommerce' ) => '%AttributeSlug%',
					__( 'Previous name', 'wsal-woocommerce' ) => '%OldName%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9061,
				WSAL_LOW,
				__( 'User changed the default sort order of an attribute', 'wsal-woocommerce' ),
				__( 'Changed the Default Sorting Order of the attribute %AttributeName% in WooCommerce to %NewSortOrder%.', 'wsal-woocommerce' ),
				array(
					__( 'Attribute slug', 'wsal-woocommerce' ) => '%AttributeSlug%',
					__( 'Previous sorting order', 'wsal-woocommerce' ) => '%OldSortOrder%',
				),
				array(),
				'woocommerce-store',
				'modified',
			),
			array(
				9062,
				WSAL_LOW,
				__( 'User enabled/disabled the option Enable Archives of an attribute', 'wsal-woocommerce' ),
				__( 'Changed the status of the option Enable Archives in WooCommerce attribute %AttributeName%.', 'wsal-woocommerce' ),
				array(
					__( 'Attribute slug', 'wsal-woocommerce' ) => '%Slug%',
				),
				array(),
				'woocommerce-store',
				'enabled',
			),
		),

		__( 'Coupons', 'wsal-woocommerce' )          => array(
			array(
				9063,
				WSAL_LOW,
				__( 'User published a new coupon', 'wsal-woocommerce' ),
				__( 'Created the WooCommerce coupon: %CouponName%.', 'wsal-woocommerce' ),
				array(),
				array(
					__( 'View coupon in editor', 'wsal-woocommerce' ) => '%EditorLinkCoupon%',
				),
				'woocommerce-coupon',
				'published',
			),
			array(
				9064,
				WSAL_LOW,
				__( 'User changed the discount type of a coupon', 'wsal-woocommerce' ),
				__( 'Changed the Discount Type in the coupon %CouponName% to %NewDiscountType%.%', 'wsal-woocommerce' ),
				array(
					__( 'Previous discount type', 'wsal-woocommerce' ) => '%OldDiscountType%',
				),
				array(
					'%EditorLinkCoupon%',
				),
				'woocommerce-coupon',
				'modified',
			),
			array(
				9065,
				WSAL_LOW,
				__( 'User changed the coupon amount of a coupon', 'wsal-woocommerce' ),
				__( 'Changed the Coupon amount in the coupon %CouponName% to %NewAmount%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous amount', 'wsal-woocommerce' ) => '%OldAmount%',
				),
				array(
					__( 'View coupon in editor', 'wsal-woocommerce' ) => '%EditorLinkCoupon%',
				),
				'woocommerce-coupon',
				'modified',
			),
			array(
				9066,
				WSAL_LOW,
				__( 'User changed the coupon expire date of a coupon', 'wsal-woocommerce' ),
				__( 'Changed the expire date of the coupon %CouponName% to %NewDate%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous date', 'wsal-woocommerce' ) => '%OldDate%',
				),
				array(
					__( 'View coupon in editor', 'wsal-woocommerce' ) => '%EditorLinkCoupon%',
				),
				'woocommerce-coupon',
				'modified',
			),
			array(
				9067,
				WSAL_LOW,
				__( 'User changed the usage restriction settings of a coupon', 'wsal-woocommerce' ),
				__( 'Changed the <strong>Usage restriction</strong> of the coupon %CouponName% to %NewMetaValue%.', 'wsal-woocommerce' ),
				array(
					__( 'Usage restriction parameter', 'wsal-woocommerce' ) => '%MetaKey%',
					__( 'Previous value', 'wsal-woocommerce' ) => '%OldMetaValue%',
				),
				array(
					__( 'View coupon in editor', 'wsal-woocommerce' ) => '%EditorLinkCoupon%',
				),
				'woocommerce-coupon',
				'modified',
			),
			array(
				9068,
				WSAL_LOW,
				__( 'User changed the usage limits settings of a coupon', 'wsal-woocommerce' ),
				__( 'Change the <strong>Usage limits</strong> of the coupon %CouponName% to %NewMetaValue%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous usage limits', 'wsal-woocommerce' ) => '%OldMetaValue%',
				),
				array(
					__( 'View coupon in editor', 'wsal-woocommerce' ) => '%EditorLinkCoupon%',
				),
				'woocommerce-store',
				'modified',
			),
			array(
				9069,
				WSAL_INFORMATIONAL,
				__( 'User changed the description of a coupon', 'wsal-woocommerce' ),
				__( 'Changed the description of the coupon %CouponName%.', 'wsal-woocommerce' ),
				array(
					__( 'Previous description', 'wsal-woocommerce' ) => '%OldDescription%',
					__( 'New description', 'wsal-woocommerce' ) => '%NewDescription%',
				),
				array(
					__( 'View coupon in editor', 'wsal-woocommerce' ) => '%EditorLinkCoupon%',
				),
				'woocommerce-coupon',
				'modified',
			),
			array(
				9070,
				E_WARNING,
				__( 'User changed the status of a coupon', 'wsal-woocommerce' ),
				__( 'Changed the status of WooCommerce coupon %CouponName%', 'wsal-woocommerce' ),
				array(
					__( 'Old status', 'wsal-woocommerce' ) => '%OldStatus%',
					__( 'New status', 'wsal-woocommerce' ) => '%NewStatus%',
				),
				array(),
				'woocommerce-coupon',
				'modified',
			),
			array(
				9071,
				WSAL_INFORMATIONAL,
				__( 'User renamed a WooCommerce coupon', 'wsal-woocommerce' ),
				__( 'Renamed the coupon %OldName% to %NewName%.', 'wsal-woocommerce' ),
				array(),
				array(
					__( 'View coupon in editor', 'wsal-woocommerce' ) => '%EditorLinkCoupon%',
				),
				'woocommerce-coupon',
				'renamed',
			),
		),

		__( 'Orders', 'wsal-woocommerce' )           => array(
			array(
				9035,
				WSAL_LOW,
				__( 'A WooCommerce order has been placed', 'wsal-woocommerce' ),
				__( 'A new order has been placed.', 'wsal-woocommerce' ),
				array(
					__( 'Order name', 'wsal-woocommerce' ) => '%OrderTitle%',
				),
				array(
					__( 'View order', 'wsal-woocommerce' ) => '%EditorLinkOrder%',
				),
				'woocommerce-order',
				'created',
			),
			array(
				9036,
				WSAL_INFORMATIONAL,
				__( 'WooCommerce order status changed', 'wsal-woocommerce' ),
				__( 'Marked the order %OrderTitle% as %OrderStatus%.', 'wsal-woocommerce' ),
				array(),
				array(
					__( 'View order', 'wsal-woocommerce' ) => '%EditorLinkOrder%',
				),
				'woocommerce-order',
				'modified',
			),
			array(
				9037,
				WSAL_MEDIUM,
				__( 'User moved a WooCommerce order to trash', 'wsal-woocommerce' ),
				__( 'Moved the order %OrderTitle% to trash', 'wsal-woocommerce' ),
				array(),
				array(
					__( 'View order', 'wsal-woocommerce' ) => '%EditorLinkOrder%',
				),
				'woocommerce-order',
				'deleted',
			),
			array(
				9038,
				WSAL_LOW,
				__( 'User moved a WooCommerce order out of trash', 'wsal-woocommerce' ),
				__( 'Restored the order %OrderTitle% out of the trash.', 'wsal-woocommerce' ),
				array(),
				array(
					__( 'View order', 'wsal-woocommerce' ) => '%EditorLinkOrder%',
				),
				'woocommerce-order',
				'restored',
			),
			array(
				9039,
				WSAL_LOW,
				__( 'User permanently deleted a WooCommerce order', 'wsal-woocommerce' ),
				__( 'Permanently deleted the order %OrderTitle%.', 'wsal-woocommerce' ),
				array(),
				array(),
				'woocommerce-order',
				'deleted',
			),
			array(
				9040,
				WSAL_MEDIUM,
				__( 'User edited a WooCommerce order', 'wsal-woocommerce' ),
				__( 'Changed the details in order %OrderTitle%.', 'wsal-woocommerce' ),
				array(),
				array(
					__( 'View order', 'wsal-woocommerce' ) => '%EditorLinkOrder%',
				),
				'woocommerce-order',
				'modified',
			),
			array(
				9041,
				WSAL_HIGH,
				__( 'User refunded a WooCommerce order', 'wsal-woocommerce' ),
				__( 'Refunded the order %OrderTitle%.', 'wsal-woocommerce' ),
				array(),
				array(
					__( 'View order', 'wsal-woocommerce' ) => '%EditorLinkOrder%',
				),
				'woocommerce-order',
				'modified',
			),
			array(
				9120,
				WSAL_HIGH,
				__( 'User added/removed a product from an order', 'wsal-woocommerce' ),
				__( 'The product %ProductTitle% to/from the order %OrderTitle%.', 'wsal-woocommerce' ),
				array(),
				array(
					__( 'View order', 'wsal-woocommerce' ) => '%EditorLinkOrder%',
				),
				'woocommerce-order',
				'added',
			),
		),

		__( 'User Profile', 'wsal-woocommerce' )     => array(
			array(
				9083,
				WSAL_INFORMATIONAL,
				__( 'User changed the billing address details', 'wsal-woocommerce' ),
				__( 'Changed <strong>billing address</strong> details of the user %TargetUsername%', 'wsal-woocommerce' ),
				array(
					__( 'Role', 'wsal-woocommerce' ) => '%Roles%',
					__( 'Previous billing address', 'wsal-woocommerce' ) => '%OldValue%',
					__( 'New Billing address', 'wsal-woocommerce' ) => '%NewValue%',
				),
				array(
					__( 'User profile page', 'wsal-woocommerce' ) => '%EditUserLink%',
				),
				'user',
				'modified',
			),
			array(
				9084,
				WSAL_INFORMATIONAL,
				__( 'User changed the shipping address details', 'wsal-woocommerce' ),
				__( 'Changed the <strong>shipping address</strong> details of the user %TargetUsername%', 'wsal-woocommerce' ),
				array(
					__( 'Role', 'wsal-woocommerce' ) => '%Roles%',
					__( 'Previous shipping address', 'wsal-woocommerce' ) => '%OldValue%',
					__( 'New Shipping address', 'wsal-woocommerce' ) => '%NewValue%',
				),
				array(
					__( 'User profile page', 'wsal-woocommerce' ) => '%EditUserLink%',
				),
				'user',
				'modified',
			),
		),
	),
);
